<style>
    comment_text {
        color: #7CFC00;
        font-size: 15px;
        font-weight: normal;
        font-style: italic;
        font-family: "Courier New";
    } byte {
        color: #FF0000;
        font-size: 15px;
        font-weight: normal;
        font-style: normal;
        font-family: "Courier New";
    } body {
        background-color: #696969;
    }
</style>

<body><title>byte.smef.pw</title>

<byte>
<!--          Change VVV for desired junk amount -->
<?php for ($total=0; 100 > $total ; $total++) { 

    $a = 1; # Amount of bytes to generate
    $type = openssl_random_pseudo_bytes; # Type of code
    
    $junk = $type($a);
    $hex = $junk;
    $byte = bin2hex($hex);
    
    # I know the above code CAN be shorter just for people who do not know about PHP that is techically easily to edit
    print "__asm _emit 0x" . $byte . " \\<br>";
} ?>
</byte>

<comment_text>// Bytes generated by smef.cc<br>// Download source here: https://github.com/smefcc/Simple-Byte-Generator</comment_text>

</body>
